### Get Orders
GET http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com')


GET http://localhost:4004/odata/v4/manage-orders/Orders

### Create Orders
POST http://localhost:4004/odata/v4/manage-orders/Orders HTTP/1.1
Content-Type: application/json

{
    "ClientEmail": "client5@client5.com",
    "FirstName": "David",
    "LastName": "Ramirez",
    "CreatedOn": "2024-03-26"
}

### Update Order
PUT http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com') HTTP/1.1
Content-Type: application/json

{
    "FirstName": "Daniel Updated",
    "LastName": "Ojados Updated"
}

### DELETE Order
DELETE http://localhost:4004/odata/v4/manage-orders/Orders('client5@client5.com')

### Get Customer Rate - Function
GET http://localhost:4004/odata/v4/manage-orders/getClientTaxRate(ClientEmail='client1@client1.com')

### Cancel Order - Action
POST http://localhost:4004/odata/v4/manage-orders/cancelOrder
Content-Type: application/json

{
    "clientEmail": "client2@client2.com"
}

### Get Customer Rate - Function
GET http://localhost:4004/odata/v4/manage-orders/Orders('client2@client2.com')/ManageOrders.getClientTaxRate(ClientEmail='client1@client1.com')

### Cancel Order - Action
POST http://localhost:4004/odata/v4/manage-orders/Orders('client2@client2.com')/ManageOrders.cancelOrder
Content-Type: application/json

{
    "clientEmail": "client2@client2.com"

}

### Get Incidents
GET http://localhost:4004/odata/v4/sapbackend-exit/Incidents